
name: E2E Test

on:
  workflow_call:
    inputs:
      WORKING_DIR:
        required: false
        type: string
        default: '.'
      HEALTHCHECK_ENDPOINT:
        required: false
        type: string
        default: 'localhost:3000'
      HEALTHCHECK_URLS:
        required: false
        type: string
        default: '/healthz'

jobs:
  e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run docker-compose
        run: |
          docker-compose up --build -d --quiet-pull --no-color
          sudo apt update -yqq && sudo apt install net-tools netcat -yqq
          docker-compose logs
          docker-compose ps
          netstat -antlp | grep LISTEN
          listening_port=`echo ${{ inputs.HEALTHCHECK_ENDPOINT }} |awk -F':' '{print $2}'`
          if [[ -z $listening_port ]]; then
            listening_port=80
          fi
          nc -vv -w 3 127.0.0.1 $listening_port || true
      - name: Test app
        env:
          ENDPOINT: ${{ inputs.HEALTHCHECK_ENDPOINT }}
        run: |
          urls=(`echo ${{ inputs.HEALTHCHECK_URLS }}`)
          for url in "${urls[@]}"; do
            echo "[INFO] url=${url}"
            status_code=$(curl --write-out '%{http_code}' -s --output /dev/null http://${ENDPOINT}${url})
            if [[ $status_code == "200" ]]; then
              echo "[INFO] status_code=${status_code}"
            else
              echo "[ERROR] url=${url} status_code=${status_code}"
              exit 1
            fi
          done