name: Unit Test

on:
  workflow_call:
    inputs:
      WORKING_DIR:
        required: false
        type: string
        default: '.'

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore dependencies cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run tests
        run: npm test